version: "3"

services:
  db:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      PGDATA: /tmp
    volumes:
      - ./tablescripts:/docker-entrypoint-initdb.d
      - ./tmp/data:/var/lib/postgresql/data
